### ISSUE TITLE
Unable to load notification icon image

### ISSUE THREAD

**Issue by tbraun96** [rafaelsetragni/awesome_notifications#111]
In ``pubspec.yaml``, I have declared:

```
assets:
    - assets/
```

Within the folder ``assets``, I have an image ``notification.png``. I load it as such:

```
    AwesomeNotifications().initialize(
        'resource://notification.png',
      [
        NotificationChannel(
            channelKey: NOTIFICATION_CHANNEL,
            channelName: 'Verisend| Messages',
            channelDescription: 'Notification channel for messages and events',
            defaultColor: primaryColor(),
            ledColor: primaryColor()
        )
      ]
    );
```

I have also tried: ``assets/notification.png`` over ``resource://notification.png``. However, ``initialize`` throws an error, and all future notification push attempts fails. The error message:

```
W/System.err(22904): java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
W/System.err(22904): 	at me.carda.awesome_notifications.utils.BitmapUtils.getDrawableResourceId(BitmapUtils.java:96)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.setSmallIcon(NotificationBuilder.java:500)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.getNotificationBuilderFromModel(NotificationBuilder.java:204)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.createNotification(NotificationBuilder.java:84)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationSender.showNotification(NotificationSender.java:190)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:121)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:25)
W/System.err(22904): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err(22904): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(22904): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err(22904): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(22904): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(22904): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(22904): java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=basic_channel pri=1 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0xff9575cd vis=UNKNOWN(2) semFlags=0x0 semPriority=0 semMissedCount=0)
W/System.err(22904): 	at android.app.NotificationManager.fixNotification(NotificationManager.java:537)
W/System.err(22904): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:516)
W/System.err(22904): 	at android.app.NotificationManager.notify(NotificationManager.java:449)
W/System.err(22904): 	at android.app.NotificationManager.notify(NotificationManager.java:425)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationSender.showNotification(NotificationSender.java:194)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:121)
W/System.err(22904): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:25)
W/System.err(22904): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err(22904): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(22904): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err(22904): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(22904): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(22904): 	at java.lang.Thread.run(Thread.java:919)
```

What am I doing wrong?

**Comment by rafaelsetragni** [comment]
The resource is not correctely placed inside the native resource directory. For android you need to put the files inside the `android/app/src/main/res/drawable` folder

**Comment by charlesRmajor** [comment]
> The resource is not correctely placed inside the native resource directory. For android you need to put the files inside the `android/app/src/main/res/drawable` folder

I think it would be helpful if that full path was included in the main README
