### ISSUE TITLE
Notifications not showing in production

### ISSUE THREAD

**Issue by Surk217** [rafaelsetragni/awesome_notifications#178]
Hello all,
so the plugin worked perfectly in debugging mode but now when testing in production mode the notification just don't show.
Can anyone help?

**Comment by rafaelsetragni** [comment]
What command are you using to generate your production app, what platform and what version?

**Comment by imSanjaySoni** [comment]
> What command are you using to generate your production app, what platform and what version?
> 
> Commonly those problems that just happen on production mode happen because of [source code minification and obfuscation](https://developer.android.com/studio/build/shrink-code). You need to protect your source media, such as icons, sounds and images, from that minification process with the tag "res_" before the name, as described on our [Media Source Types README Topic](https://github.com/rafaelsetragni/awesome_notifications#media-source-types)

**same problem**
I am using command this for release build  ``` flutter build appbundle```

**Comment by jja08111** [comment]
Same issue here!
Some day, I could not create any notification in release mode(`flutter run --release` and `flutter build appbundle`)!
So I found this issue and #29, but adding `res_` in my icon data didn't solve this problem.  I use the newest plugin version(0.0.6+9).

Do I need to add the `_res` prefix to **all files** in the `res` folder other than icon used for notifications?

### Log
```command
I/flutter (29363): PlatformException(createNewNotification, The notification channel 'bedtime_reminder' do not exist or is disabled, h.a.a.e.f.a: The notification channel 'bedtime_reminder' do not exist or is disabled
I/flutter (29363):      at h.a.a.a.c(:2)
I/flutter (29363):      at h.a.a.a.onMethodCall(:15)
I/flutter (29363):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage()
I/flutter (29363):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart()
I/flutter (29363):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage()
I/flutter (29363):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (29363):      at android.os.MessageQueue.next(MessageQueue.java:323)
I/flutter (29363):      at android.os.Looper.loop(Looper.java:136)
I/flutter (29363):      at android.app.ActivityThread.main(ActivityThread.java:6682)
I/flutter (29363):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter (29363):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
I/flutter (29363):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
I/flutter (29363): , null)
```

### flutter doctor --verbose
```command
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1110], locale ko-KR)
    • Flutter version 2.2.2 at C:\flutter
    • Framework revision d79295af24 (5 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\AndroidSDK
    • Platform android-S, build-tools 30.0.2
    • ANDROID_HOME = C:\AndroidSDK
    • ANDROID_SDK_ROOT = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • SM G925S (mobile) • 0715f71511b4013a • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 91.0.864.70

• No issues found!
```
