### ISSUE TITLE
Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference

### ISSUE THREAD

**Issue by dokumanx** [rafaelsetragni/awesome_notifications#191]
**Describe the bug**
When I catch the notification from FCM, after calling `await AwesomeNotifications()
        .createNotificationFromJsonData(remoteMessage.data);` , I am getting this error.
```
[   +1 ms] W/System.err(32483): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
[   +4 ms] W/System.err(32483): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.getNotificationTargetActivityClass(NotificationBuilder.java:391)
[        ] W/System.err(32483): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.buildNotificationIntentFromModel(NotificationBuilder.java:95)
[   +2 ms] W/System.err(32483): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.createNotification(NotificationBuilder.java:62)
[        ] W/System.err(32483): 	at me.carda.awesome_notifications.notifications.NotificationSender.showNotification(NotificationSender.java:207)
[        ] W/System.err(32483): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:127)
[        ] W/System.err(32483): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:31)
[   +1 ms] W/System.err(32483): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[   +1 ms] W/System.err(32483): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[        ] W/System.err(32483): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
[        ] W/System.err(32483): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[   +1 ms] W/System.err(32483): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] W/System.err(32483): 	at java.lang.Thread.run(Thread.java:923)

```

**Dependencies**

Flutter sdk version: 2.0.5
Dart sdk version: ">=2.10.0 <3.0.0"
firebase_core: ^1.2.1
firebase_messaging: ^10.0.1
awesome_notifications: ^0.0.6+7

**Expected behavior**

It should display notification.

**Sample code to reproduce the problem**

Below code my notification service.
```dart
import 'dart:io';

import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:meh/constants/constants.dart';

final AwesomeNotifications awesomeNotifications = AwesomeNotifications();

class NotificationService {
  final _messaging = FirebaseMessaging.instance;

  void initialize() async {

    awesomeNotifications.initialize(null, [
      NotificationChannel(
        channelKey: 'Meh',
        channelName: 'Meh',
        channelDescription: "I Say Meh",
        defaultColor: Colors.red,
      )
    ]);

    await _messaging.setForegroundNotificationPresentationOptions(sound: true);

    awesomeNotifications.isNotificationAllowed().then((isAllowed) {
      if (!isAllowed) {
        if (Platform.isIOS) {
          _messaging.requestPermission();
        }
        // TODO: Insert here your friendly dialog box before call the request method
        // This is very important to not harm the user experience
        awesomeNotifications.requestPermissionToSendNotifications();
      }
    });

    //TODO: Handle token with createDevice mutation later.
    final token = await _messaging.getToken(vapidKey: vapidKey);

    final remoteMessage = await _messaging.getInitialMessage();

    _handleRemoteMessage(remoteMessage: remoteMessage);

    FirebaseMessaging.onMessage.listen(
      (remoteMessage) => _handleRemoteMessage(remoteMessage: remoteMessage),
    );

    FirebaseMessaging.onBackgroundMessage((remoteMessage) async {
      if (remoteMessage != null) {
        _handleRemoteMessage(remoteMessage: remoteMessage);
      }
    });
  }
}

Future<void> _handleRemoteMessage({RemoteMessage remoteMessage}) async {
  await Firebase.initializeApp();
  if (remoteMessage != null) {
    // final notification = remoteMessage?.notification;
    final isCreated = await AwesomeNotifications()
        .createNotificationFromJsonData(remoteMessage.data);
    if (isCreated) {
      print(
          '############################## NOTIFICATION SUCCESSFULLY CREATED ##############################');
    }
  }
}


```

**Comment by rafaelsetragni** [comment]
```Java
    public Class getNotificationTargetActivityClass(Context context) {
        String packageName = context.getPackageName();
        Intent launchIntent = context.getPackageManager().getLaunchIntentForPackage(packageName);
        String className =
                launchIntent == null ?
                packageName + ".MainActivity" :
                launchIntent.getComponent().getClassName();
        try {
            return Class.forName(className);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            return null;
        }
    }
```

Thanks! This fix will be released in the next version.

**Comment by dokumanx** [comment]
Where should I use the code you have attached? And what causes this issue? Is it related with my dependency versions or something else? Can you give me further information? Thanks.

**Comment by rafaelsetragni** [comment]
Yes, you should use it until i release a new version.

This method is responsible to determine the target class that all the notifications should go. For flutter applications there always a main target class, but for some reason on your app the method `getLaunchIntentForPackage` wasnt capable to find it. So, i put the standard class `MainActivity` of every flutter project to be the target. Is the best that i can do from a plugin to determine the app target.

**Comment by dokumanx** [comment]
I am not familiar with the Android. Here is my MainActivity.kt. Can you show me how I can add the code you have provided?

```kotlin
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine!!)
    }
}


```

**Comment by rafaelsetragni** [comment]
Click on `AwesomeNotifification()` method with Ctrl hold and you should be redirect to the file inside your machine. Click with the right mouse button hover the file name and ask for where the file is placed inside your local machine. So, go to android folder and change this method.

**Comment by rafaelsetragni** [comment]
Also, try to add this permission into your `AndroidManifest.xml` file:

```Xml
<category android:name="android.intent.category.LAUNCHER" />
```

**Comment by dokumanx** [comment]
So, I went into `AwesomeNotification()`. Then I found where it is located. I went into the android folder. But it is still not clear to me where should I add this method. Can you give me the file's location and which part of the code should be replaced with the one given by you?

**Comment by rafaelsetragni** [comment]
But i really dont get why the method `getLaunchIntentForPackage` could not get the main class name even inside your own ap. I guess is important to you to discovery why this do not happened.

Open your android folder with Android Studio and debug your source to verify whats goin on. The list with all plugins will be availabe at your left after first project gradle loading.

**Comment by dokumanx** [comment]
Do you want me to share `AndroidManifest.xml`, `build.gradle` or something else? I can share any file if it will give you further information about what is going on. FIY, I had the same issue with `flutter_local_notifications`.

**Comment by rafaelsetragni** [comment]
Send me a e-mail with a meet call and ill help you to solve it.
rafaelsetra@gmail.com

**Comment by dokumanx** [comment]
Alright. I have just sent.
