### ISSUE TITLE
Small icon must be a valid media native resource type.

### ISSUE THREAD

**Issue by nietsmmar** [rafaelsetragni/awesome_notifications#214]
I am using version `0.0.6+9` and this is my code:

```
AwesomeNotifications().createNotification(
          content: NotificationContent(
              id: 1,
              channelKey: 'myChannelKey',
              title: "MyTitle",
              body: "MyBody",
              icon: "https://www.w3schools.com/howto/img_avatar2.png", 
              payload: {"myPayloadItem": "true"}));
```

I get this error:
```
me.carda.awesome_notifications.notifications.exceptions.AwesomeNotificationException: Small icon ('https://www.w3schools.com/howto/img_avatar2.png') must be a valid media native resource type.
at me.carda.awesome_notifications.notifications.models.NotificationContentModel.validateIcon(NotificationContentModel.java:247)
at me.carda.awesome_notifications.notifications.models.NotificationContentModel.validate(NotificationContentModel.java:215)
at me.carda.awesome_notifications.notifications.models.PushNotification.validate(PushNotification.java:134)
at me.carda.awesome_notifications.notifications.NotificationSender.send(NotificationSender.java:76)
at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodCreateNotification(AwesomeNotificationsPlugin.java:870)
at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:518)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

But the `readme` says, that a network link should be a valid resource type. What am I doing wrong? Thanks alot!

**Comment by imSanjaySoni** [comment]
I think this is because using a network image ("https://www.w3schools.com/howto/img_avatar2.png"). for the small icon, the image should be using local only. you can use other options res, assets, or file.

**Comment by nietsmmar** [comment]
Oh okay, thanks for this hint!
