### ISSUE TITLE
Error NotificationChannel.getImportance()

### ISSUE THREAD

**Issue by Alejandro9415** [rafaelsetragni/awesome_notifications#28]
Hello, good morning, first of all, thank you very much for such a good notification package. Second, I had a problem, the library was working well at the beginning, then it started with this error that I show below, what could it be?

Exception has occurred.
PlatformException (PlatformException(Notification not created, Attempt to invoke virtual method 'int android.app.NotificationChannel.getImportance()' on a null object reference, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.NotificationChannel.getImportance()' on a null object reference
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.isNotificationEnabled(AwesomeNotificationsPlugin.java:714)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodCreateNotification(AwesomeNotificationsPlugin.java:633)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:406)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:147)
	at android.app.ActivityThread.main(ActivityThread.java:6749)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
, null))

**Comment by rafaelsetragni** [comment]
Yes, it's a bug! Excuse me.

You are trying to recover a notification channel that no longer exists, and I forgot to check if the channel is different from null at this point.

I'm going to put an update in the master repository, fixing it now.

**Comment by rafaelsetragni** [comment]
I release the 0.0.4+3 version, with this bug fixed.

**Comment by Alejandro9415** [comment]
Hello good day, not at the moment I did not find any related problem because honestly the library is very good it was the best I found but if it is missing it is documentation since for example I need to create notifications with buttons and I had to review the example and so I could Implement but the rest no more and I could not go with the notification of firebase I implemented it as it has in the documentation for android and the notification does not arrive I could make it arrive but it does not arrive with the buttons

**Comment by rafaelsetragni** [comment]
Yes, im improving the documentation, specially when i discovery here where people are getting confusing.
Some colaborator did a really good  and simple example and i gonna put in the documentation as well.

In soon ill publish an new version 0.0.5, more simple to implement in iOS, more complete and with documentation improved.

**Comment by Alejandro9415** [comment]
thanks

**Comment by rafaelsetragni** [comment]
Version 0.0.5 finally released!

But you gonna need to protect your native resources against minification inserting the prefix "res_" in your image or sound file names. You can see more about it [here in the README file](https://github.com/rafaelsetragni/awesome_notifications#media-source-types).

Also i simplified the iOS installation. Please, update it if you pretend to use iOS too.

Call me here if you continue with issues on this new version.
