### ISSUE TITLE
Scheduled notification error

### ISSUE THREAD

**Issue by mdikcinar** [rafaelsetragni/awesome_notifications#280]
Hi, my created scheduled notifications works on ios, android 11(mi 9t) and 12(emulator) but I am getting error on Huawei mate 20 lite which has android 10 and android 9(mi 6).

this is my example code;
`var timeZone = await AwesomeNotifications().getLocalTimeZoneIdentifier();
      await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: 1,
            channelKey: 'scheduled_timer_channel',
            title: title,
            locked: true,
            body: LocaleKeys.notificationEasySet.locale,
            autoCancel: false,
            payload: {'exerciseUuid': '$exerciseUuid', 'currentSetIndex': '$currentSetIndex'}),
        actionButtons: [
          NotificationActionButton(
              key: btnKeyDone,
              label: LocaleKeys.notificationDone.locale,
              autoCancel: true,
              buttonType: ActionButtonType.KeepOnTop),
          NotificationActionButton(key: btnKeyFailed, label: LocaleKeys.notificationFailed.locale, autoCancel: true),
        ],
        schedule: NotificationInterval(interval: 10, timeZone: timeZone, repeats: false, allowWhileIdle: false),
      );`

and this is the error; 
`W/System.err( 8754): me.carda.awesome_notifications.notifications.exceptions.AwesomeNotificationException: Interval is required and must be greater than zero
W/System.err( 8754): 	at me.carda.awesome_notifications.notifications.models.NotificationIntervalModel.validate(NotificationIntervalModel.java:58)
W/System.err( 8754): 	at me.carda.awesome_notifications.notifications.models.PushNotification.validate(PushNotification.java:137)
W/System.err( 8754): 	at me.carda.awesome_notifications.notifications.NotificationSender.send(NotificationSender.java:76)
W/System.err( 8754): 	at me.carda.awesome_notifications.notifications.NotificationSender.send(NotificationSender.java:51)
W/System.err( 8754): 	at me.carda.awesome_notifications.notifications.broadcastReceivers.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:35)
W/System.err( 8754): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4349)
W/System.err( 8754): 	at android.app.ActivityThread.access$2500(ActivityThread.java:296)
W/System.err( 8754): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2238)
W/System.err( 8754): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err( 8754): 	at android.os.Looper.loop(Looper.java:213)
W/System.err( 8754): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err( 8754): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8754): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
`

I have fixed the issue by using NotificationCalender instead of NotificationInterval.
`schedule: NotificationCalendar.fromDate(date: DateTime.now().add(Duration(seconds: failureSetTime))),`

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
