### ISSUE TITLE
Choose custom sound from android storage

### ISSUE THREAD

**Issue by rheadavin** [rafaelsetragni/awesome_notifications#323]
Hi, I'm making an app with notifications. I want users to be able to select custom sounds through their storage. Is it possible with this plugin? Do you have a reference for that? Thank you very much

**Comment by rafaelsetragni** [comment]
Yes, its possible. But you need to remember that each platform accepts different file types, and you must to storage then in the right place for each platform.

**Comment by rheadavin** [comment]
Could you give me some reference for that?

**Comment by rafaelsetragni** [comment]
No. I haven't seen anyone implementing it. You gonna need to do it by your own.

**Comment by rheadavin** [comment]
I tried with file_picker and path_provider. After I pick the audio, I copied it to another directory.  This is my code:
`Future<void> openOfflineMusicSelectionDialog(context) async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.audio);

    if (result != null) {
      PlatformFile file = result.files.first;
      if (file.path != null) {
        final newFile = await saveFileAfterPick(file);
        
        await AwesomeNotifications().setChannel(
          NotificationChannel(
            channelKey: 'alarm_notification_3',
            channelName: 'Alarm Notification Custom',
            channelDescription: 'Notification channel for alarm',
            defaultColor: Color(0xFFFFDA2B),
            ledColor: Colors.white,
            vibrationPattern: highVibrationPattern,
            importance: NotificationImportance.Max,
            soundSource: newFile.path.toString(),
            playSound: true
          ),
        );
      }
    } else {
      // User canceled the picker
    }
  }

  Future<File> saveFileAfterPick(PlatformFile file) async{
    final appStorage = await getApplicationDocumentsDirectory();
    final newFile = File('${appStorage.path}/${file.name}');
    return File(file.path!).copy(newFile.path);
  }`

When I pick the audio file with .mp3 extention, I got a error like this:
`PlatformException (PlatformException(setNotificationChannel, Audio media is not valid, me.carda.awesome_notifications.notifications.exceptions.AwesomeNotificationException: Audio media is not valid
	at me.carda.awesome_notifications.notifications.models.NotificationChannelModel.validate(NotificationChannelModel.java:270)
	at me.carda.awesome_notifications.notifications.managers.ChannelManager.saveChannel(ChannelManager.java:93)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodSetChannel(AwesomeNotificationsPlugin.java:724)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:513)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:331)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
, null))`

What have I missed?

**Comment by rafaelsetragni** [comment]
Channels are designed to only be setted once, for the newer Android devices you will not able to change it. To use dynamic sounds for each notification, is more indicate to use the property customSound in the notification content.

To use a sound, you need to include "resource://" in front of the file name. Unfortunately, I still haven't been able to specify the sounds by files, as I did with the images.

And you need to be aware of what sound types each platform accept.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by AbdullahAli1993** [comment]
Hi, @rheadavin did you find a way to specify a custom sound from the Android storage?
