### ISSUE TITLE
setChannel with forceUpdate throws Exception

### ISSUE THREAD

**Issue by t1ooo** [rafaelsetragni/awesome_notifications#405]
Flutter version: 2.8.1
Package version: ^0.6.21
Device: Android 10 (API 29) (emulator)
Run with `flutter run -d android`

```dart
import 'package:flutter/material.dart';
import 'package:awesome_notifications/awesome_notifications.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final notificationChannel = NotificationChannel(
    channelKey: 'key',
    channelName: 'name',
    channelDescription: 'description',
  );
  await AwesomeNotifications().initialize(null, [notificationChannel]);
  await AwesomeNotifications().setChannel(
    notificationChannel,
    forceUpdate: true, // work when false
  );
}
```

Output
```
W/System.err( 8310): java.lang.ArrayIndexOutOfBoundsException: length=3; index=-1000
W/System.err( 8310): 	at me.carda.awesome_notifications.notifications.managers.ChannelManager.androidChannelNeedsForceUpdate(ChannelManager.java:247)
W/System.err( 8310): 	at me.carda.awesome_notifications.notifications.managers.ChannelManager.saveAndroidChannel(ChannelManager.java:198)
W/System.err( 8310): 	at me.carda.awesome_notifications.notifications.managers.ChannelManager.saveChannel(ChannelManager.java:165)
W/System.err( 8310): 	at me.carda.awesome_notifications.notifications.managers.ChannelManager.saveChannel(ChannelManager.java:130)
W/System.err( 8310): 	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodSetChannel(AwesomeNotificationsPlugin.java:711)
W/System.err( 8310): 	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:498)
W/System.err( 8310): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err( 8310): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
W/System.err( 8310): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
W/System.err( 8310): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
W/System.err( 8310): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err( 8310): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 8310): 	at android.os.Looper.loop(Looper.java:214)
W/System.err( 8310): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err( 8310): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8310): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 8310): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

https://github.com/rafaelsetragni/awesome_notifications/blob/3f5c77193d2ad47fb8d49e677a1fa9a37b9dd6bb/android/src/main/java/me/carda/awesome_notifications/notifications/managers/ChannelManager.java#L247

**Comment by rafaelsetragni** [comment]
You don't need to set the channel after initialize and only use force channel in last case.

**Comment by t1ooo** [comment]
Сould you please write a code sample? How to force update channel correctly? Thanks.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
