### ISSUE TITLE
Audio media is not valid in Android

### ISSUE THREAD

**Issue by maksumon** [rafaelsetragni/awesome_notifications#426]
I have added custom sound for Android notification in **res/res_sound.m4a** but on initialize getting following exception and notification is not working:

`me.carda.awesome_notifications.notifications.exceptions.AwesomeNotificationException: Audio media is not valid
	at me.carda.awesome_notifications.notifications.models.NotificationChannelModel.validate(NotificationChannelModel.java:286)
	at me.carda.awesome_notifications.notifications.managers.ChannelManager.saveChannel(ChannelManager.java:136)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.setChannels(AwesomeNotificationsPlugin.java:1145)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.setDefaultConfigurations(AwesomeNotificationsPlugin.java:1088)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodInitialize(AwesomeNotificationsPlugin.java:1070)
	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:438)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)`

Initialized notification channel as follows:
`NotificationChannel(
        channelKey: 'android_sound_channel',
        channelName: 'Android Custom Sound Notifications',
        channelDescription: 'Notification channel for Android Custom Sound',
        playSound: true,
        soundSource: 'resource://raw/res_sound',
        defaultColor: Colors.green,
        ledColor: Colors.white,
        importance: NotificationImportance.Max,
),`

**Note: I have converted the sound from mp3 to m4a and it's working fine in macOS with iTunes and other players.**

**Comment by maksumon** [comment]
I copy over the customer sound file to the android emulator and it plays without any issue.

**Comment by rafaelsetragni** [comment]
I have an example app that uses all awesome notifications features, including custom sounds. Tou can try to run it or take a look on how i did it.

And you need to remember that, for Android 8+, the sound is defined by notification channels and, once defined, it cannot be changed anymore.

**Comment by maksumon** [comment]
@rafaelsetragni Actually, the issue was because of the iOS sound source. I am using the different channels for iOS and Android.

**Comment by Muhammed-Ayad** [comment]
@maksumon 
hello 
How did you solve the problem?
