### ISSUE TITLE
Notification not showing when using  ( requireInputText: true) in android 12.

### ISSUE THREAD

**Issue by arv-aks** [rafaelsetragni/awesome_notifications#439]
version:-      awesome_notifications: ^0.7.0-beta.1

W/System.err(29141): java.lang.IllegalArgumentException: 0|com.osunio|10|null|12723 Not posted. PendingIntents attached to actions with remote inputs must be mutable
W/System.err(29141):    at android.os.Parcel.createExceptionOrNull(Parcel.java:2441)
W/System.err(29141):    at android.os.Parcel.createException(Parcel.java:2421)
W/System.err(29141):    at android.os.Parcel.readException(Parcel.java:2404)
W/System.err(29141):    at android.os.Parcel.readException(Parcel.java:2346)
W/System.err(29141):    at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:4238)
W/System.err(29141):    at android.app.NotificationManager.notifyAsUser(NotificationManager.java:696)
W/System.err(29141):    at android.app.NotificationManager.notify(NotificationManager.java:631)
W/System.err(29141):    at android.app.NotificationManager.notify(NotificationManager.java:607)
W/System.err(29141):    at me.carda.awesome_notifications.awesome_notifications_core.managers.StatusBarManager.showNotificationOnStatusBar(StatusBarManager.java:89)
W/System.err(29141):    at me.carda.awesome_notifications.awesome_notifications_core.threads.NotificationSender.showNotification(NotificationSender.java:226)
W/System.err(29141):    at me.carda.awesome_notifications.awesome_notifications_core.threads.NotificationSender.doInBackground(NotificationSender.java:132)
W/System.err(29141):    at me.carda.awesome_notifications.awesome_notifications_core.threads.NotificationSender.doInBackground(NotificationSender.java:27)
W/System.err(29141):    at me.carda.awesome_notifications.awesome_notifications_core.threads.NotificationThread.executeNotificationThread(NotificationThread.java:16)
W/System.err(29141):    at me.carda.awesome_notifications.awesome_notifications_core.threads.NotificationSender.send(NotificationSender.java:85)
W/System.err(29141):    at me.carda.awesome_notifications.awesome_notifications_core.AwesomeNotifications.createNotification(AwesomeNotifications.java:565)
W/System.err(29141):    at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodCreateNotification(AwesomeNotificationsPlugin.java:853)
W/System.err(29141):    at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:236)
W/System.err(29141):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(29141):    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
W/System.err(29141):    at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
W/System.err(29141):    at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
W/System.err(29141):    at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(29141):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(29141):    at android.os.Looper.loopOnce(Looper.java:226)
W/System.err(29141):    at android.os.Looper.loop(Looper.java:313)
W/System.err(29141):    at android.app.ActivityThread.main(ActivityThread.java:8633)
W/System.err(29141):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(29141):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
W/System.err(29141):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
W/System.err(29141): Caused by: android.os.RemoteException: Remote stack trace:
W/System.err(29141):    at com.android.server.notification.NotificationManagerService.checkDisqualifyingFeatures(NotificationManagerService.java:7878)
W/System.err(29141):    at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:7566)
W/System.err(29141):    at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:7329)
W/System.err(29141):    at com.android.server.notification.NotificationManagerService$14.enqueueNotificationWithTag(NotificationManagerService.java:4088)
W/System.err(29141):    at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1580)

**Comment by arv-aks** [comment]
solved this by updating - PendingIntent.FLAG_IMMUTABLE to FLAG_MUTABLE in (NotificationBuilder.java)
[awesome_notifications/android/src/main/java/me/carda/awesome_notifications/notifications/NotificationBuilder.java]

 actionPendingIntent =
                    actionType == ActionType.Default ?
                        PendingIntent.getActivity(
                                context,
                                notificationModel.content.id,
                                actionIntent,
                                (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) ?
                                        PendingIntent.FLAG_IMMUTABLE | PendingIntent.FLAG_UPDATE_CURRENT :
                                        PendingIntent.FLAG_UPDATE_CURRENT)
                            :
//change below (PendingIntent.FLAG_IMMUTABLE) to (PendingIntent.FLAG_MUTABLE)  when using requireInputText = true. for (android 12)
                        PendingIntent.getBroadcast(
                                context,
                                notificationModel.content.id,
                                actionIntent,
                                (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) ?
                                        PendingIntent.FLAG_MUTABLE | PendingIntent.FLAG_UPDATE_CURRENT :
                                        PendingIntent.FLAG_UPDATE_CURRENT);
