### ISSUE TITLE
App fails to set listeners

### ISSUE THREAD

**Issue by pires22** [rafaelsetragni/awesome_notifications#459]
On emulator it's working fine, but on my real device this error happens:

```
E/flutter ( 3919): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Instance of 'IsolateCallbackException'
E/flutter ( 3919): #0      receiveSilentAction
package:awesome_notifications/…/isolates/isolate_main.dart:78
E/flutter ( 3919): #1      AwesomeNotifications._handleMethod
package:awesome_notifications/src/awesome_notifications_core.dart:219
E/flutter ( 3919): #2      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:414
E/flutter ( 3919): #3      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:407
E/flutter ( 3919): #4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:377
E/flutter ( 3919): #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:374
E/flutter ( 3919): #6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
E/flutter ( 3919): #7      _rootRun (dart:async/zone.dart:1426:13)
E/flutter ( 3919): #8      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 3919): #9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 3919): #10     _invoke2 (dart:ui/hooks.dart:189:10)
E/flutter ( 3919): #11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter ( 3919): #12     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter ( 3919): #13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter ( 3919): #14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
E/flutter ( 3919): #15     _dispatchPlatformMessage `(dart:ui/hooks.dart:89:31)
```

I'm setting the listeners here:

```
@override
  void initState() {
    super.initState();
    AwesomeNotifications().setListeners(
        onCreatedNotificationMethod: MyApp.onCreatedNotificationMethod,
        onDisplayedNotificationMethod: MyApp.onDisplayedNotificationMethod,
        onActionNotificationMethod: MyApp.onActionNotificationMethod,
        onDismissedNotificationMethod: MyApp.onDismissedNotificationMethod);
    print("done");
  }
```

And this is the class with the listeners:

```
class MyApp extends StatefulWidget {
  MyApp();

  static final GlobalKey<NavigatorState> navigatorKey =
      GlobalKey<NavigatorState>();

  static String name = 'Awesome Notifications - Example App';
  static Color mainColor = Color(0xFF9D50DD);

  static Future<void> onCreatedNotificationMethod(
      ReceivedNotification receivedNotification) async {
    /// This replaces createdStream
  }

  static Future<void> onDisplayedNotificationMethod(
      ReceivedNotification receivedNotification) async {
    /// This replaces displayedStream
  }

  static Future<void> onDismissedNotificationMethod(
      ReceivedAction receivedAction) async {
    /// This replaces dismissedStream
  }

  static Future<void> onActionNotificationMethod(
      ReceivedAction receivedAction) async {
    {
      /// This replaces actionStream
      switch (receivedAction.notificationActionType) {

        // Default Notification behavior, that brings the app to foreground
        case NotificationActionType.BringToForeground:
          // your code goes here
          break;

        // Do not bring the app to foreground and do not work with app killed
        case NotificationActionType.KeepOnTopAction:
          // your code goes here
          break;

        // Receive silent notification actions without bring the app to foreground
        case NotificationActionType.SilentAction: // Runs on main thread
           WidgetsFlutterBinding.ensureInitialized();
          return;
        case NotificationActionType
            .SilentBackgroundAction: // Runs on background thread (without UI)
           WidgetsFlutterBinding.ensureInitialized();
          return;

        // disabled actions never reach this point, they die
        // at native level.
        case NotificationActionType.DisabledAction:
        default:
          break;
      }
    }
  }

  @override
  State<MyApp> createState() => _MyAppState();
}
```

It actually prints done, but the error occurs when I send a SilentAction or a SilentBackgroundAction from a notification.

I couldn't manage to set the navigatorKey on my app, I don't know if thats a problem. It's an app with just the home screen anyway.

**Comment by rafaelsetragni** [comment]
At this point, it prints this message:

> Could not find a valid action callback. Certifies that your action method is global and static.

According to the source codes pasted here, is everything right. But seems at that point in your real device, awesome couldn't find a valid global static function to execute.

Try to uninstall the app in the emulator and clean your flutter project, and then try again in the emulator, to ensure this issue do not happen on the emulator.

**Comment by pires22** [comment]
U ran the steps below:

```
1 - run flutter clean
2 - open emulator and uninstall the old app
3 - start debugging
```

The emulator works fine, everything as it should be.

When I tried to debug it in my real device tho, it doesn't even install the app anymore, I don't know if it's an issue with adb or something. But I generated an apk with `flutter build apk` and installed it manually.

Unfortunately, it doesn't works. And I'm not able to see the errors too because I'm not debugging.

My emulator is running Android 10, and my real device is also running Android 10.

I can create a repo with my app if you need.

**Comment by pires22** [comment]
I changed to:
```
awesome_notifications:
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: 0f93123
```

Output of flutter pub get:

```
Package not available (the pubspec for awesome_notifications 0.7.0-beta.2 from git has version 0.6.21).
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Package not available (the pubspec for awesome_notifications 0.7.0-beta.2 from git has version 0.6.21).
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Package not available (the pubspec for awesome_notifications 0.7.0-beta.2 from git has version 0.6.21).
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
```

I tried to use other references but it gives me the same errors. The only one I could use was `009770e`

**Comment by pires22** [comment]
Update:

I tried to debug the app on another computer.
First, it gave me the same error as #389 except that in his solution he had to degrade gradle build tools to 4.1.* and mine was already 4.1.* so I couldn't do that. Then I upgraded my gradle version on `gradle-wrapper.properties` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip` and I could debug and install the app on an emulator.

And for my surprise: it didn't work! It gave me the same error of my first message.

On my main computer emulator it's working fine and I can provide you a video if you need.

What info do you need to analyze this situation?

**Comment by pires22** [comment]
Solved using this version:

```
awesome_notifications: 0.7.0-beta.2
```

Keep up the good work Rafael.
