### ISSUE TITLE
Notification channel 'basic_channel' does not exist., n.a.a.k.f.a:

### ISSUE THREAD

**Issue by tamannaBelymon** [rafaelsetragni/awesome_notifications#482]
I/flutter ( 5032): PlatformException(createNewNotification, Notification channel 'basic_channel' does not exist., n.a.a.k.f.a: Notification channel 'basic_channel' does not exist.
I/flutter ( 5032): 	at n.a.a.k.i.g.i(:5)
I/flutter ( 5032): 	at n.a.a.k.i.k.i(Unknown Source:4)
I/flutter ( 5032): 	at n.a.a.k.d.b(Unknown Source:10)
I/flutter ( 5032): 	at n.a.a.f.f(:2)
I/flutter ( 5032): 	at n.a.a.f.onMethodCall(:42)
I/flutter ( 5032): 	at l.a.d.a.w.a(Unknown Source:17)
I/flutter ( 5032): 	at io.flutter.embedding.engine.n.g.e(Unknown Source:17)
I/flutter ( 5032): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
I/flutter ( 5032): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 5032): 	at android.os.MessageQueue.next(MessageQueue.java:335)
I/flutter ( 5032): 	at android.os.Looper.loopOnce(Looper.java:161)
I/flutter ( 5032): 	at android.os.Looper.loop(Looper.java:288)
I/flutter ( 5032): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
I/flutter ( 5032): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 5032): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
I/flutter ( 5032): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/flutter ( 5032): , null)
Exited

Flutter awesome notification not worked in release-apk, code works perfect in debug. please help.

**Comment by tamannaBelymon** [comment]
No , I haven't change anything in android Folder, I made changes in android folder which mention by package. I just keep Code as per package.

**Comment by tamannaBelymon** [comment]
**android/build.gradle**

`buildscript {
    ext.kotlin_version = '1.4.32'
    repositories {
        google()
        jcenter()

    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`


**android/app/build.gradle**

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.bebuzee"
        minSdkVersion 24
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
//            shrinkResources false
//            minifyEnabled false
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-messaging:20.1.0'
}
apply plugin: 'com.google.gms.google-services'`

**Comment by Babsky** [comment]
I also have this problem now but I can't even get it to work in debug. I had version 0.6.10 so updated to 0.6.21 but it's the same.
I'm getting:  
Android Emulator
W/System.err( 5070): me.carda.awesome_notifications.notifications.exceptions.AwesomeNotificationException: Notification channel 'appname_key' does not exist.

iOS Simulator
flutter: PlatformException(exception, Unknow error, The operation couldn’t be completed. (awesome_notifications.AwesomeNotificationsException error 1.), null)

**Comment by deepak16paliwal** [comment]
did anyOne get proper solution for this issue
