### ISSUE TITLE
Crash on Fatal Exception: java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by LondonX** [rafaelsetragni/awesome_notifications#507]
When calling on `ChannelManager$androidChannelNeedsUpdate` on Android platform App crash. 
```
Fatal Exception: java.lang.IncompatibleClassChangeError: The method 'boolean java.lang.Object.equals(java.lang.Object)' was expected to be of type interface but instead was found to be of type virtual (declaration of 'ci.d' appears in /data/app/com.xxxxxxxxxx.xxx-pf3kfUpOmWmEUh25xxxx==/base.apk:classes2.dex)
       at me.carda.awesome_notifications.notifications.managers.ChannelManager.androidChannelNeedsUpdate(ChannelManager.java:234)
       at me.carda.awesome_notifications.notifications.managers.ChannelManager.saveAndroidChannel(ChannelManager.java:207)
       at me.carda.awesome_notifications.notifications.managers.ChannelManager.saveChannel(ChannelManager.java:165)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.setChannels(AwesomeNotificationsPlugin.java:1145)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.setDefaultConfigurations(AwesomeNotificationsPlugin.java:1088)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodInitialize(AwesomeNotificationsPlugin.java:1070)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:438)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
       at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$TsixYUB5E6FpKhMtCSQVHKE89gQ(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$ceffc6bae7d364cb48afaf1aaebd60bf9050360d0efb9035ebc54f0851df0a05$0.run(DartMessenger.java:12)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Follow the logs I think the problem is caused by comparing `CharSquence` with `String`
```
androidChannel.getName().equals(channelModel.channelName)
```
Can I fix it by changing this line into`androidChannel.getName().toString().equals(channelModel.channelName)`?

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
