### ISSUE TITLE
Android - NullPointerException when schedule notification from background action button

### ISSUE THREAD

**Issue by ansshkki** [rafaelsetragni/awesome_notifications#548]
Starting from version `0.7.0-beta.2` on Android, when I make a background action to schedule another notification I get this error:

<details>
  <summary>Stack Trace</summary>

  ```
  D/Android: [Awesome Notifications]( 6303): Awesome Notifications plugin attached to Android 30 (AwesomeNotificationsPlugin:115)
  D/Android: [Awesome Notifications]( 6303): Awesome Notifications attached to engine for Android 30 (AwesomeNotificationsPlugin:97)
  I/Android: [Awesome Notifications]( 6303): Executing background FlutterEngine instance. (DartBackgroundExec:180)
  I/flutter ( 6303): [🌎 Easy Localization] [DEBUG] Start
  I/flutter ( 6303): [🌎 Easy Localization] [DEBUG] Build
  I/flutter ( 6303): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
  I/flutter ( 6303): [🌎 Easy Localization] [DEBUG] Init provider
  E/Android: [Awesome Notifications]( 6303): Attempt to invoke virtual method 'int java.util.TimeZone.getOffset(long)' on a null object reference (AwesomeNotificationsPlugin:58)
  I/flutter ( 6303): [Awesome Notifications - ERROR]: Got an unknown Silent Action callback error: PlatformException(UNKNOWN_EXCEPTION, Attempt to invoke virtual method 'int java.util.TimeZone.getOffset(long)' on a null object reference, unexpectedError.NullPointerException, null) (receiveSilentAction:87)
  I/flutter ( 6303): [Awesome Notifications - ERROR]: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
  I/flutter ( 6303): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #2      AwesomeNotifications.createNotification (package:awesome_notifications/src/awesome_notifications_core.dart:233:29)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #3      NotificationController._scheduleSnoozedNotification (package:saleem/src/core/helpers/notifications_helper.dart:434:5)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #4      NotificationController.onActionReceivedMethod (package:saleem/src/core/helpers/notifications_helper.dart:413:7)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #5      receiveSilentAction (package:awesome_notifications/src/isolates/isolate_main.dart:85:5)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #6      channelMethodSilentCallbackHandle (package:awesome_notifications/src/isolates/isolate_main.dart:52:20)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #7      dartIsolateMain.<anonymous closure> (package:awes
  I/flutter ( 6303): [Awesome Notifications - ERROR]: An error occurred in your background messaging handler: Instance of 'AwesomeNotificationsException' (channelMethodSilentCallbackHandle:59)
  I/flutter ( 6303): [Awesome Notifications - ERROR]: #0      channelMethodSilentCallbackHandle (package:awesome_notifications/src/isolates/isolate_main.dart:56:7)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #1      dartIsolateMain.<anonymous closure> (package:awesome_notifications/src/isolates/isolate_main.dart:24:9)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #2      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:404:42)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303): #3      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:22)
  I/flutter ( 6303): <asynchronous suspension>
  I/flutter ( 6303):  (receiveSilentAction:61)
  I/Android: [Awesome Notifications]( 6303): All silent data fetched. (DartBackgroundExec:246)
  I/Android: [Awesome Notifications]( 6303): Shutting down background FlutterEngine instance. (DartBackgroundExec:208)
  D/Android: [Awesome Notifications]( 6303): Awesome Notifications plugin detached from Android 30 (AwesomeNotificationsPlugin:140)
  I/Android: [Awesome Notifications]( 6303): FlutterEngine instance terminated. (DartBackgroundExec:215)
  ```

</details>

For more details, my action button is meant to snooze the notification, it takes snooze length from shared preferences and schedule new notification.

This is the code I use for that:

```dart
static Future<void> onActionReceivedMethod(ReceivedAction action) async {
  if (action.buttonKeyPressed == notificationActionSnooze) {
    final id = action.id;
    final title = action.title;
    final body = action.body;
    final payload = action.payload;
    if (id == null || title == null || body == null) return;
    await _scheduleSnoozedNotification(id, title, body, payload);
  }
}

...

  static Future<void> _scheduleSnoozedNotification(int id, String title, String body, Map<String, String?>? payload) async {
    final preferences = await SharedPreferences.getInstance();
    final s = preferences.getInt("snooze_length") ?? 1;
    await AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: id + NotificationsHelper.snoozeIdOffset,
        channelKey: channelId,
        title: title,
        body: body,
        category: NotificationCategory.Reminder,
        payload: payload,
      ),
      schedule: NotificationInterval(
        interval: s * 30 * 60,
        repeats: false,
        allowWhileIdle: true,
        timeZone: AwesomeNotifications.localTimeZoneIdentifier,
      ),
      actionButtons: [
        NotificationActionButton(
          key: habitNotificationActionSnooze,
          label: payload?[notificationActionSnooze] ?? "Snooze",
          actionType: ActionType.SilentBackgroundAction,
        ),
        NotificationActionButton(
          key: habitNotificationActionDone,
          label: payload?[notificationActionDone] ?? "Done",
          actionType: ActionType.SilentBackgroundAction,
        ),
        NotificationActionButton(
          key: habitNotificationActionDismiss,
          label: payload?[notificationActionDismiss] ?? "Dismiss",
          actionType: ActionType.DisabledAction,
        ),
      ],
    );
  }
```

**NOTE 1:** As you can see from the snippet code, I have two more action buttons and they are working correctly.

**NOTE 2:** the same code is working correctly on iOS.

**NOTE 3:** I tried all the versions starting with `0.7.0-beta.1` to the latest version until now `0.7.0-beta.6+1`, only `beta.1` worked for the same code.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
