### ISSUE TITLE
App crashing with java.lang.NoSuchMethodException: R7.k.values

### ISSUE THREAD

**Issue by helloalbin** [rafaelsetragni/awesome_notifications#721]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **App crashing with java.lang.NoSuchMethodException: R7.k.values

`Fatal Exception: java.lang.ExceptionInInitializerError:
       at me.carda.awesome_notifications.core.managers.LifeCycleManager.<clinit>(LifeCycleManager.java:21)
       at me.carda.awesome_notifications.core.managers.LifeCycleManager.getInstance(LifeCycleManager.java:34)
       at me.carda.awesome_notifications.core.AwesomeNotifications.<init>(AwesomeNotifications.java:105)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.AttachAwesomeNotificationsPlugin(AwesomeNotificationsPlugin.java:152)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onAttachedToEngine(AwesomeNotificationsPlugin.java:129)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
       at com.app.MainActivity.configureFlutterEngine(MainActivity.java:35)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:206)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:495)
       at com.app.MainActivity.onCreate(MainActivity.java:22)
       at android.app.Activity.performCreate(Activity.java:8290)
       at android.app.Activity.performCreate(Activity.java:8270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Fatal Exception: java.lang.ExceptionInInitializerError:
       at me.carda.awesome_notifications.core.managers.LifeCycleManager.<clinit>(LifeCycleManager.java:21)
       at me.carda.awesome_notifications.core.managers.LifeCycleManager.getInstance(LifeCycleManager.java:34)
       at me.carda.awesome_notifications.core.AwesomeNotifications.<init>(AwesomeNotifications.java:105)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.AttachAwesomeNotificationsPlugin(AwesomeNotificationsPlugin.java:152)
       at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onAttachedToEngine(AwesomeNotificationsPlugin.java:129)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
       at com.app.MainActivity.configureFlutterEngine(MainActivity.java:35)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:206)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:495)
       at com.app.MainActivity.onCreate(MainActivity.java:22)
       at android.app.Activity.performCreate(Activity.java:8290)
       at android.app.Activity.performCreate(Activity.java:8270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins) : 
Only notification plugin is awesome_notifications

* What platform did you found the issue
Android 12
* What devices did you found the issue
Samsung Galaxy A32 5G

* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2364], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.0)
[!] Android Studio (version 2022.1)
    X Unable to find bundled Java version.
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.

**Comment by rafaelsetragni** [comment]
Hello,

Could you please provide us with the plugin version you're currently using? Because currently there is no attribute or function called `values` being used within the LifeCycleManager class. It's possible that this discrepancy might be due to this specific plugin version with an error that was already solved.

**Comment by WojuadeAA** [comment]
Hello, i am facing this issue on version ^0.7.4+1

**Comment by AbhiAppBuddy** [comment]
I got this issue


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\deali\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\awesome_notifications-0.7.5-dev.1\android\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':awesome_notifications'.
> Project with path ':awn_core' could not be found in project ':awesome_notifications'.

**Comment by rafaelsetragni** [comment]
Hi @AbhiAppBuddy, @WojuadeAA and @helloalbin, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.
