### ISSUE TITLE
getAllActiveNotificationIdsOnStatusBar() crash the app

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#802]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

Running 
`await AwesomeNotifications().getAllActiveNotificationIdsOnStatusBar()` crash the app.
Probably code missing handling seneriao where there is no notification on status bar.

OBS: avoid to use the expression **"its not working"** or **"is working"** or any other variation. These expressions can mean anything and at same time doesn´t bring any useful information. As soon you rewrite these expressions, you naturally going to be more precise and clear.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
Notification plugins only contains `awesome_notifications: ^0.7.5-dev.3` and `awesome_notifications_fcm: ^0.7.5-dev.3`.
No non `awesome_notifications` notification plugin is in use

* What platform did you found the issue
Android

* What devices did you found the issue
Android emulator

* How are you initializing the plugin

* How are you creating the notification
The problem is not with creating notifications so not relevant.

* The output of `flutter doctor` command
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-IL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2022.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

Error

```dart
E/Android: [Awesome Notifications](15344): Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference (AwesomeNotificationsPlugin:58)
E/flutter (15344): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(UNKNOWN_EXCEPTION, Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference, unexpectedError.NullPointerException, null)
E/flutter (15344): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (15344): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (15344): <asynchronous suspension>
E/flutter (15344): #2      MethodChannelAwesomeNotifications.getAllActiveNotificationIdsOnStatusBar (package:awesome_notifications/awesome_notifications_method_channel.dart:507:12)
E/flutter (15344): <asynchronous suspension>
E/flutter (15344): #3      AppNotificationService._handleNotificationsWhenAppOpens (package:users_app/core/app_notification_service.dart:387:19)
E/flutter (15344): <asynchronous suspension>
E/flutter (15344): #4      AppNotificationService.initNotifications (package:users_app/core/app_notification_service.dart:63:5)
E/flutter (15344): <asynchronous suspension>
E/flutter (15344): #5      start (package:users_app/main.dart:23:3)
E/flutter (15344): <asynchronous suspension>
E/flutter (15344): 
```

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

## **6 - Additional context**

Tested on version 
`awesome_notifications: ^0.7.5-dev.3`
and also 
`awesome_notifications: ^0.7.4+1`

**Comment by guyluz11** [comment]
Should not get closed

**Comment by guyluz11** [comment]
.
