### ISSUE TITLE
Cannot load AwesomePodFile Error after running 'flutter build ios' 

### ISSUE THREAD

**Issue by am2074** [rafaelsetragni/awesome_notifications#932]
After inserting the necessary changes needed on the podfile and running the 'flutter build ios' command right with 'flutter clean' and 'flutter pub get' prior, I keep getting the following error:

CocoaPods' output:
↳

    [!] Invalid `Podfile` file: cannot load such file --
    flutter_project_name/ios/plugins/awesome_notifications/ios/Scripts/AwesomePodFile.

     #  from /flutter_project_name/ios/Podfile:59
     #  -------------------------------------------
     #  awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'))
     >  require awesome_pod_file
     #  update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
     #  -------------------------------------------

I've tried the 'flutter build ios' command with the changes needed in the podfile for Awesome Notifications removed and it was able to do so just fine. I've tried other versions of Awesome Notifications to no avail.

**Comment by mmirio** [comment]
I had such a problem, I included _awesome_notifications_  and _awesome_notifications_core_ at the same time.
Add only one dependency _awesome_notifications_  and do 
```
flutter clean 
flutter pub get 
pod install  (from ios folder)
flutter run 
```

**Comment by am2074** [comment]
No luck. I used _awesome_notifications_ and did not include the core dependency. I'm still getting the same error, even when running pod install in the _ios_ directory. What version of _awesome_notifications_ would you happen to be using?

**Comment by am2074** [comment]
Thanks! Looks like this method works. I will note that I didn't do _pod install_ from the ios folder. I just ran _flutter build ios_.

**Comment by VarPDev** [comment]
@am2074  I have the same error

with command `pod install`

```
pod install --repo-update --project-directory=ios


[!] Invalid `Podfile` file: cannot load such file -- /Users/pasquale.delucia/Apps/scuolazooviaggi_app/.symlinks/plugins/awesome_notifications/ios/Scripts/AwesomePodFile.

 #  from /Users/pasquale.delucia/Apps/scuolazooviaggi_app/ios/Podfile:55
 #  -------------------------------------------
 #  awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
 >  require awesome_pod_file
 #  update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
 #  -------------------------------------------
```

with command `flutter build ios`

```
Building com.scuolazoo.travel for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode
project: 37CLX8358U
Running pod install...                                             926ms
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: cannot load such file --
    /Users/pasquale.delucia/Apps/scuolazooviaggi_app/ios/.symlinks/plugins/awesome_notifications/
    ios/Scripts/AwesomePodFile.

     #  from /Users/pasquale.delucia/Apps/scuolazooviaggi_app/ios/Podfile:55
     #  -------------------------------------------
     #  awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios',
     'Scripts', 'AwesomePodFile'), '.symlinks')
     >  require awesome_pod_file
     #  update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)),
     flutter_root)
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:335:in
    `rescue in block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:329:in
    `block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in
    `instance_eval'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in
    `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in
    `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in
    `from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:293:in
    `from_file'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in
    `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
```

**Comment by breezymind** [comment]
> I have the same error

I have the same error

**Comment by nikkieke** [comment]
> @mmirio I have the same error
> 
> with command `pod install`
> 
> ```
> pod install --repo-update --project-directory=ios
> 
> 
> [!] Invalid `Podfile` file: cannot load such file -- /Users/pasquale.delucia/Apps/scuolazooviaggi_app/.symlinks/plugins/awesome_notifications/ios/Scripts/AwesomePodFile.
> 
>  #  from /Users/pasquale.delucia/Apps/scuolazooviaggi_app/ios/Podfile:55
>  #  -------------------------------------------
>  #  awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
>  >  require awesome_pod_file
>  #  update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
>  #  -------------------------------------------
> ```
> 
> with command `flutter build ios`
> 
> ```
> Building com.scuolazoo.travel for device (ios-release)...
> Automatically signing iOS for device deployment using specified development team in Xcode
> project: 37CLX8358U
> Running pod install...                                             926ms
> CocoaPods' output:
> ↳
> 
>     [!] Invalid `Podfile` file: cannot load such file --
>     /Users/pasquale.delucia/Apps/scuolazooviaggi_app/ios/.symlinks/plugins/awesome_notifications/
>     ios/Scripts/AwesomePodFile.
> 
>      #  from /Users/pasquale.delucia/Apps/scuolazooviaggi_app/ios/Podfile:55
>      #  -------------------------------------------
>      #  awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios',
>      'Scripts', 'AwesomePodFile'), '.symlinks')
>      >  require awesome_pod_file
>      #  update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)),
>      flutter_root)
>      #  -------------------------------------------
> 
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:335:in
>     `rescue in block in from_ruby'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:329:in
>     `block in from_ruby'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in
>     `instance_eval'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in
>     `initialize'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in
>     `new'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in
>     `from_ruby'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:293:in
>     `from_file'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in
>     `verify_podfile_exists!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
>     /usr/local/bin/pod:23:in `load'
>     /usr/local/bin/pod:23:in `<main>'
> 
> Error running pod install
> ```
> 
> this is the part of my pod file I modified for awesome notification
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
>     ################  Awesome Notifications pod modification 1 ###################
>     awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
>     require awesome_pod_file
>     update_awesome_pod_build_settings(installer)
>     ################  Awesome Notifications pod modification 1 ###################
> end
> 
> ################  Awesome Notifications pod modification 2 ###################
> awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
> require awesome_pod_file
> update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
> ################  Awesome Notifications pod modification 2 ###################
> ```
> 
> packages installed
> 
> ```
>   awesome_notifications_core: ^0.9.1 # <~ always ensure to use the latest version
>   awesome_notifications: any # <~ this version is managed by awesome_notifications_core package
> ```

I am having this same issue. Have you been able to fix this?
