### ISSUE TITLE
PlatformException(SHARED_PREFERENCES_NOT_AVAILABLE, class p2.b isn't parameterized, sharedPreferences.get, null)

### ISSUE THREAD

**Issue by Sebuahhobi** [rafaelsetragni/awesome_notifications#960]
I get an error when I use API 34

**Version:** awesome_notifications: ^0.9.3+1

**build.gradle**
`
android {
    namespace "com...."
    compileSdk 34
    ndkVersion '26.1.10909125'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_18
        targetCompatibility JavaVersion.VERSION_18
    }

   kotlinOptions {
       jvmTarget = '18'
   }
     kotlin {
         jvmToolchain(18)
     }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com...."
        minSdkVersion 22
        targetSdkVersion 34
        multiDexEnabled true
        versionCode 11
        versionName "1.11" 
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }

        debug {
            shrinkResources false
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    buildToolsVersion '34.0.0'
}
`

Error when I do flutter **run --release**, but when debug mode all runs normally.

I/flutter (24429): error notif init: PlatformException(SHARED_PREFERENCES_NOT_AVAILABLE, class p2.b isn't parameterized, sharedPreferences.get, null)
I/flutter (24429): Lokaasi error: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
I/flutter (24429): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
I/flutter (24429): <asynchronous suspension>
I/flutter (24429): #2      MethodChannelAwesomeNotifications.initialize (package:awesome_notifications/awesome_notifications_method_channel.dart:300)

Line 300 leads to this code:
`
var result = await methodChannel.invokeMethod(CHANNEL_METHOD_INITIALIZE, {
      INITIALIZE_DEBUG_MODE: debug,
      INITIALIZE_DEFAULT_ICON: defaultIconPath,
      INITIALIZE_CHANNELS: serializedChannels,
      INITIALIZE_CHANNELS_GROUPS: serializedChannelGroups,
      BACKGROUND_HANDLE: dartCallbackReference!.toRawHandle()
    });
`

**Comment by AntoniPochopien** [comment]
I have the same problem

**Comment by AntoniPochopien** [comment]
Does anyone know when the problem will be resolved? This is a critical issue in our application

**Comment by answer0732** [comment]
I have the same problem!  is a critical issue in our application

**Comment by azizndao** [comment]
I have the same issue. I try to manually add shared_preferences package but nothing change.

**Comment by OutdatedGuy** [comment]
This only occurs when `shrinkResources` and `minifyEnabled` is set to true. The error occurs in the `AndroidAwnCore` used within this plugin. So no idea when this will be fixed.

So if anyone wants to build the app in meantime, just set `shrinkResources` and `minifyEnabled` to false.

**Comment by answer0732** [comment]
> This only occurs when `shrinkResources` and `minifyEnabled` is set to true. The error occurs in the `AndroidAwnCore` used within this plugin. So no idea when this will be fixed.
> 
> So if anyone wants to build the app in meantime, just set `shrinkResources` and `minifyEnabled` to false.

But doing this will make my app very large, and I have to consider disabling the notification function. 😥

**Comment by OutdatedGuy** [comment]
> But doing this will make my app very large, and I have to consider disabling the notification function. 😥

Yeah, it's either having a big app or no notifications/[flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) instead (if functionality requirements are satisfied).

**Comment by OutdatedGuy** [comment]
@answer0732 can try adding the following rules to your `proguard-rules.pro` file and see if the app works fine?

```pro
# Google Guava Proguard Rules
-keep class com.google.common.reflect.TypeToken
-keep class * extends com.google.common.reflect.TypeToken
```

**Comment by answer0732** [comment]
> @answer0732 can try adding the following rules to your `proguard-rules.pro` file and see if the app works fine?
> 
> ```idl
> # Google Guava Proguard Rules
> -keep class com.google.common.reflect.TypeToken
> -keep class * extends com.google.common.reflect.TypeToken
> ```

This solution works! thanks !!!

**Comment by OutdatedGuy** [comment]
> This solution works! thanks !!!

Glad to know 🤗

> How did you come up with that? I tried for so long and couldn't find a solution.

I just posted the answers on stackoverflow:
- https://stackoverflow.com/q/78812316/15428718
- https://stackoverflow.com/a/78823627/15428718
- https://stackoverflow.com/a/78823629/15428718

Also added a PR to fix this issue natively: https://github.com/rafaelsetragni/AndroidAwnCore/pull/2

**Comment by jainAbhishek-02** [comment]
> @answer0732 can try adding the following rules to your `proguard-rules.pro` file and see if the app works fine?
> 
> ```idl
> # Google Guava Proguard Rules
> -keep class com.google.common.reflect.TypeToken
> -keep class * extends com.google.common.reflect.TypeToken
> ```

Tried this fix but getting this error now:
 Unhandled Exception: PlatformException(NOTIFICATION_THREAD_EXCEPTION, TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved., unexpectedError, null)
E/flutter (26337): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
E/flutter (26337): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
E/flutter (26337): <asynchronous suspension>
E/flutter (26337): #2      MethodChannelAwesomeNotifications.createNotification (package:awesome_notifications/awesome_notifications_method_channel.dart:102)

**Comment by OutdatedGuy** [comment]
@jainAbhishek-02 Which version of `awesome_notifications` are you using?

**Comment by selvam920** [comment]
same issue i'm also facing "NOTIFICATION_THREAD_EXCEPTION"

**Comment by jainAbhishek-02** [comment]
@OutdatedGuy  @selvam920 
using this version -> awesome_notifications: ^0.9.3+1
I made it work by setting 
```
minifyEnabled false
shrinkResources false
```
I know this is not a good solution as it will little bit increase the app size but it is working so using this.

**Comment by OutdatedGuy** [comment]
@jainAbhishek-02 @selvam920 can you try adding following rules in the `proguard-rules.pro` files and let me know if it resolves the problem.

```pro
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class com.google.common.reflect.TypeToken { *; }
```
